name: AnimeVibe Build and Test CI

on:
  push:
    branches:
      - master
      - feature/*
      - enhancement/*
  pull_request:
    branches:
      - master
      - feature/*
      - enhancement/*

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create local.properties
        run: |
            echo "jikan.url=${{ secrets.JIKAN_URL }}" > local.properties
            echo "animerunway.url=${{ secrets.ANIMERUNWAY_URL }}" >> local.properties
            echo "youtube.url=${{ secrets.YOUTUBE_URL }}" >> local.properties

      - name: Grant Gradle Execute Permissions
        run: chmod +x gradlew

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Run Lint Checks
        run: ./gradlew lintDebug

      - name: Build Debug APK
        run: ./gradlew assembleDebug